version: '2'

services:

  can-bahn-db:
    image: mongo:3.2.17
	container_name: can-bahn-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - can-bahn-tier
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - can-bahn-db:/data/db
      - can-bahn-db-dump:/dump

  can-bahn:
    image: wekanteam/wekan:latest
    container_name: can-bahn-app
    restart: always
    networks:
      - can-bahn-tier
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - METEOR_RELEASE=${METEOR_RELEASE}
        - NPM_VERSION=${NPM_VERSION}
        - ARCHITECTURE=${ARCHITECTURE}
        - SRC_PATH=${SRC_PATH}
        - METEOR_EDGE=${METEOR_EDGE}
        - USE_EDGE=${USE_EDGE}
    ports:
      - 8080:80
      - 27017:27017
    environment:
      - MONGO_URL=mongodb://can-bahndb:27017/can-bahn
      - ROOT_URL=http://john-deep.asuscomm:8080
    depends_on:
      - can-bahndb

volumes:
  can-bahn-db:
    driver: local
  can-bahn-db-dump:
    driver: local

networks:
  can-bahn-tier:
    driver: bridge
